name: emoticons
description: Use emojis in your strings.
version: 0.1.2
author: Muhammed Ali Sit <sitmuhammedali@gmail.com>
homepage: https://www.github.com/malisit/emoticons

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
